# Generated by Django 5.0.8 on 2024-08-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Mamtak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("buyer", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "flavour",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("W", "White"),
                            ("M", "Milk"),
                            ("D", "Dark"),
                            ("R", "Ruby"),
                        ],
                        max_length=1,
                    ),
                ),
                ("purchase_date", models.DateTimeField()),
                (
                    "ingredients",
                    models.ManyToManyField(blank=True, to="mamtakim_store.ingredients"),
                ),
            ],
        ),
    ]
